# goal definition
# facing ID of the facing whose products shall be counted
string id
---
# result definition
# number of products that have been counted in the facing
uint32 count

# constants used to report errors
int32 SUCCESS=0
int32 INVALID_ID=1
int32 SERVER_BUSY=2
int32 ABORTED=3
# member to report errors, uses the above defined constants
int32 error
# optional, human-readable error message
string error_msg
---
# feedback definition
# currently empty
