#Goal definition 

#Constants used to indicate the type of cropped_image.
uint8 INVALID_IMAGE=0
uint8 DEPTH_IMAGE=1
uint8 RGB_IMAGE=2

#The type of cropped_image. This has the value of one of the above constants.
uint8 image_type

sensor_msgs/CompressedImage cropped_image

---

#Result definition of the actions

int8 count

---

#Feedback
string status
