# request definition
# shelf layer ID to which the facings belong
string id
---
# response definition
# facing IDs that belong to the shelf layer of interest
string[] ids

# constants used to report errors
int32 SUCCESS=0
int32 INVALID_ID=1
# member to report errors, uses the above defined constants
int32 error
